### ISSUE TITLE
unable to open watch ttwatch-git 20161128-1

### ISSUE THREAD

**Issue by ladywithhat** [ryanbinns/ttwatch#106]
With the new build of the ttwatch-git 20161128-1 i am unable to get a connection with my spark runner 2.
FW-version: 1.3.250
Linux: archlinux

`ttwatch -v
Unable to open watch
`
Former version 20160527-1 worked perfectly.

**Comment by adzane** [comment]
Have you checked the connection? Is the watch *firmly* snapped into the cable cradle?

**Comment by ladywithhat** [comment]
@adzane lsusb shows watch and watch is charging. so I assume the watch is detected
Bus 002 Device 008: ID 1390:7475 TOMTOM B.V. 
Linux: 4.8.11-1-ARCH

Other ways to find out why ttwatch is not working?

**Comment by ryanbinns** [comment]
That's a strange situation. The latest update only revision information for use with the `--setting(s)` commands.

If you run `ttwatch --devices`, does it list your watch?

**Comment by ladywithhat** [comment]
I had to kill ttwatchd than ttwatch worked as expected. But now ttwatchd does not work anymore.
