### ISSUE TITLE
Reset formats to only to ttbin

### ISSUE THREAD

**Issue by mger** [ryanbinns/ttwatch#117]
Hey Ryan

First of all, let me thank you for this tremendously useful piece of software allowing me to throw Windows of my hard disk for good. During my use of the tool I encountered a minor issue which might be due to a bug, might have been just overlooked, or might even be due to a shortcoming from my side by not handling it correctly.

Using `ttwatch --set-formats=LIST`, one can set additional formats in which the activity files will be stored upon downloading from the watch. However, once specified, I haven't found a way of getting rid of these additional formats such that only the binary (ttbin) will be saved, as was the case initially.

Passing an empty list, that is `ttwatch --set-formats=`, yields `No valid file formats found` and thus doesn't work.

**Comment by ryanbinns** [comment]
I have removed the check to see that at least one format was specified, so `ttwatch --set-formats=` will now just clear the list.
