### ISSUE TITLE
Runner vs Multi-sport

### ISSUE THREAD

**Issue by mitnworb** [ryanbinns/ttwatch#123]
Do you know if there is a way to run the multi-sport firmware in a runner watch?  I have been doing a lot more biking and hate having to change it from run to ride before uploading to Strava.  Thanks. 

Tim

**Comment by ryanbinns** [comment]
This was discussed previously: #16 

The firmware is the same in both watches and the watch itself knows what it is. In short, if you want expensive features, buy an expensive watch!
