### ISSUE TITLE
No donation button etc.

### ISSUE THREAD

**Issue by petrkutalek** [ryanbinns/ttwatch#129]
No a real issue, nevertheless I could not find any other way to contact you.
I have not found a donation button nor something similar. You should fix that, you deserve support for what you have done for us. Thank you!

**Comment by ryanbinns** [comment]
I'll think about it, but no, I don't think I will. And no, there's no other way to contact me; it's quite intentional.

**Comment by mipapo** [comment]
Then just let me say: This project is really great! Thank you very much for your time and work you've put in here

**Comment by petrkutalek** [comment]
Exactly, thanks a lot!
