### ISSUE TITLE
Wrong steps (count/length) in treadmill

### ISSUE THREAD

**Issue by OswaldKolle1977** [ryanbinns/ttwatch#139]
Don't know, if it is only with my runs, but I get a wrong Step-Count and -Length (in treadmill):
Values: 160 spm, 0,64m (step-count: 9616)
calculated: 8 spm, 2,55m (step-count: 481)

The failure is within the "export_tcx.c".
The Code from line 265 (with my correct working version):
```
// BEGIN ORIGINAL
                if ((int)record->treadmill.steps <= 4) // max 4 * 60 = 240 spm
                    cadence_avg = (0.05 * 30 * (int)record->treadmill.steps) + (1.0 - 0.05) * cadence_avg;
                fprintf(file, "                                <RunCadence>%d</RunCadence>\r\n", (int)cadence_avg);
// END ORIGINAL
// BEGIN MW (WORKING)
//                if ((int)steps <= 4) // max 4 * 60 = 240 spm
//                    cadence_avg = (0.05 * 30 * (int)steps) + (1.0 - 0.05) * cadence_avg;
//                fprintf(file, "                                <RunCadence>%d</RunCadence>\r\n", (int)cadence_avg);
// END MW (WORKING)
 ```
It seems like the values within record->treadmill are not correct (it contains total-steps!), but the steps are...

**Comment by ryanbinns** [comment]
Yes, you're correct. I have pushed an update with the fix. Thanks for tracking this down. It's been there for a long time; I guess not many people use the treadmill function.

**Comment by OswaldKolle1977** [comment]
Thanks a lot!
