### ISSUE TITLE
[QUESTION] How to upload activity to RunKeeper?

### ISSUE THREAD

**Issue by wayneworkman** [ryanbinns/ttwatch#143]
Hello,
How would I upload activity files from my TomTom watch to RunKeeper or to TomTom's system, or Nike+ or any of those? I'm just getting started with this.
Thanks,
Wayne

**Comment by weechatter** [comment]
have a look at the "ttbin2mysports" file

**Comment by wayneworkman** [comment]
@weechatter I must be blind, it's right there on top. Thank you so much! Hopefully my question will help others that are searching the web for a solution.
