### ISSUE TITLE
New firmware release 1.7.64 from Tomtom

### ISSUE THREAD

**Issue by frankcrawford** [ryanbinns/ttwatch#149]
Tomtom have released a new version of the firmware, 1.7.64, which looks to be a minor fix for bluetooth, etc.
I've run a few quick tests with ttwatch after updating ttwatch.c definition to use the same entries as for 1.7.62, and it all seems to be fine, so you may want to consider updating it officially.

**Comment by frankcrawford** [comment]
P.S. I noticed that the manifest file manifest_0001073e.txt gives
options/tracker/goals/type = unknown (6)
Option 6 is "points"

**Comment by ryanbinns** [comment]
Thanks for the feedback. I have made these changes.
