### ISSUE TITLE
Missing heart rate data from Runner

### ISSUE THREAD

**Issue by parkerlreed** [ryanbinns/ttwatch#167]
Firmware version 1.8.52 with a Polar heart rate sensor (OH1)

Used `ttbincnv` to translate the ttbin file of the run to csv but the heart rate field is always blank.

Any ideas?

**Comment by ryanbinns** [comment]
I don't have a heart rate sensor, so I've never tried it, but I know there are people who have successfully downloaded valid heart rate data. Does the heart rate data show on your watch while you're running?

**Comment by parkerlreed** [comment]
It did yeah. It's been so long, I don't know where I put that watch or HR sensor. 

I'll close out for now unless I come back to this later.

Thanks
