### ISSUE TITLE
HR Zones settings missing in manifest

### ISSUE THREAD

**Issue by scubajorgen** [ryanbinns/ttwatch#168]
The HR zone settings (zone min max HR) as can be set on the TomTom website are missing in the manifest, at least in manifest_0001073e.txt
You can add following:

hrzone/easy/min,255,i,1,bpm,,
hrzone/easy/max,256,i,1,bpm,,
hrzone/fatburn/min,257,i,1,bpm,,
hrzone/fatburn/max,258,i,1,bpm,,
hrzone/cardio/min,259,i,1,bpm,,
hrzone/cardio/max,260,i,1,bpm,,
hrzone/perform/min,261,i,1,bpm,,
hrzone/perform/max,262,i,1,bpm,,
hrzone/peak/min,263,i,1,bpm,,
hrzone/peak/max,264,i,1,bpm,,

Typical values from my watch:
 253 unknown                                            35651584
 254 unknown                                            1
 255 hrzone/easy/min                                    87
 256 hrzone/easy/max                                    104
 257 hrzone/fatburn/min                                 105
 258 hrzone/fatburn/max                                 122
 259 hrzone/cardio/min                                  123
 260 hrzone/cardio/max                                  139
 261 hrzone/perform/min                                 140
 262 hrzone/perform/max                                 157
 263 hrzone/peak/min                                    158
 264 hrzone/peak/max                                    174
 265 running/training/zones/heart/custom/low            110

The percentages as mentioned with the settings on the TomTom MySports site with the HR values do not appear in the settings list. When I change them no alterations appear when I connect the watch to the MySports application.

**Comment by ryanbinns** [comment]
Thanks. I've added them to the manifest file.
