### ISSUE TITLE
ttbincnv: Unable to read and parse TTBIN file

### ISSUE THREAD

**Issue by dfkki123508** [ryanbinns/ttwatch#179]
When executed on [this file](https://we.tl/t-68hYC0KGlA) via
```
./ttbincnv -t 00910000_20231029_142253.ttbin
```
ttbincnv returns
```
Unable to read and parse TTBIN file
```

Any ideas why? Did the file format change? Thanks!

**Comment by ryanbinns** [comment]
Nothing has changed for years as far as I know. I don't have a TomTom watch anymore, so I haven't been able to test it properly for at least 3 years.

**Comment by dfkki123508** [comment]
Sorry, my bad. I took the pre-built binary... Building ttbincnv from source solved the problem.
