### ISSUE TITLE
Latest firmware...

### ISSUE THREAD

**Issue by dbrb2** [ryanbinns/ttwatch#20]
Afternoon
It looks like the manifest definition on the latest firmware (1.8.35) isn't recognize by your code. Hardly surprising, I think the new firmware was only released sometime last week....hopefully only the ID, bot the manifest structure, has actually changed...

**Comment by ryanbinns** [comment]
I have updated the manifest list to include this new watch version.

Cheers,
Ryan

**Comment by dbrb2** [comment]
Thanks :-)
