### ISSUE TITLE
Segmentation fault in ttbincnv

### ISSUE THREAD

**Issue by weechatter** [ryanbinns/ttwatch#28]
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000406131 in export_kml (ttbin=0x16f92e0, file=0x1967060) at export_kml.c:253
253                 if ((ttbin->gps_records.records[i]->gps.timestamp != 0) &&
(gdb) bt
#0  0x0000000000406131 in export_kml (ttbin=0x16f92e0, file=0x1967060) at export_kml.c:253
#1  0x0000000000401d41 in main (argc=3, argv=0x7ffda0082058) at ttbincnv.c:220

**Comment by ryanbinns** [comment]
Fixed. A copy-and-paste error :blush:

**Comment by weechatter** [comment]
Confirmed, fixed! Thanks a lot
