### ISSUE TITLE
About elevation data from altimeter

### ISSUE THREAD

**Issue by sezamoid** [ryanbinns/ttwatch#36]
First thank you for your great work, I am very happy to be able to use my watch on Linux.

I don't know if it is really a ttwatch issue, but I am trying to see if we can make use of the elevation values recorded by the watch altimeter (mine have one). Once the activity is finished there is no way to see it, which is a bit disappointing.

I am trying to look at the values in the altitude struct when reading my ttbin file but it seems to contain random data. Do you think that ttbin files created by watches with altimeter may contain any usefull elevation data? If not is there any chance to extract it from the watch?

Cheers,

**Comment by ryanbinns** [comment]
The watch does not provide altimeter data. There is no way to get an altimeter reading. The altimeter data is only used by the watch to calculate calories burned. The altitude information is downloaded from a digital elevation model based on recorded lat/long position.
