### ISSUE TITLE
Unable to download elevation data

### ISSUE THREAD

**Issue by weechatter** [ryanbinns/ttwatch#46]
Any idea why this happens:

Downloading elevation data
Unable to download elevation data: 56
Unable to write file formats: fit

**Comment by ryanbinns** [comment]
Error code 56 (from the libcurl library) is a generic receive error. It's usually similar to the connection reset messages you get in web browsers, but in reality it could be one of many errors with receiving data. I've never seen it myself. It could be a flaky internet connection or maybe TomTom's web server had a hiccup, but it's not anything to do with the ttwatch software itself.

You can skip the elevation data download using the ttbincnv program, giving it the -E (or --no-elevation) command line option.
