### ISSUE TITLE
ttbincnv renames file (not just extension), stops ttbin2mysports.sh from working

### ISSUE THREAD

**Issue by mjsearle** [ryanbinns/ttwatch#47]
Had to modify line 62 in ttbin2mysports.sh to this
( cd "${dir}" && cat "${file}.ttbin" | ttbincnv -t >"${file}.tcx" )

as default behaviour of ttbincnv is to rename file to {activity type}_{code}.tcx

Otherwise good work. All working for me on Ubuntu 15.04

**Comment by ryanbinns** [comment]
Thanks for the feedback. I don't use MySports and I didn't write that script, so I've never noticed. It should work if the ttbin files haven't been renamed though.

I'll make the change, unless you'd like to submit a pull request and I'll merge it.

**Comment by mjsearle** [comment]
Happy for you to make the change. Thanks.  I've done plently of scripting
but are new to Git. The script worked fine once I made that change. The
workouts all appeared on my MapMyFittness dashboard after the script
uploaded them.

**Comment by ryanbinns** [comment]
I've committed a fix for this. Can you verify it when you have a chance please? My watch has died and is in for repair :-(

**Comment by mjsearle** [comment]
Made a fresh clone. Worked fine. Thanks.
