### ISSUE TITLE
convert other file formats to ttbin

### ISSUE THREAD

**Issue by weechatter** [ryanbinns/ttwatch#51]
is this somehow possible with ttbincnv?

**Comment by ryanbinns** [comment]
I don't currently have any plans to support this, and I haven't yet thought how it would be useful. Do you have a specific reason why you need this?

**Comment by weechatter** [comment]
its a bit related to https://github.com/ryanbinns/ttwatch/issues/50

Currently its not possible to upload races created with pacecreator to mysports. converting the pacecreator gpx file to ttbin makes it possible to upload it as a normal run to mysports and then using it as a race file.

And as we all know TomTom is not the fastest in fixing problems :-(
