### ISSUE TITLE
Heart rate recovery

### ISSUE THREAD

**Issue by uded** [ryanbinns/ttwatch#54]
In the comment only two values are stated: 3 and 4.

The values, according to my observations, ranges from 1 to 4. Therefore: poor, decent, good and excellent recovery. Worth mentioning somewhere...

**Comment by ryanbinns** [comment]
Yep, I'll change it. I don't have a heart rate sensor, so I relied on someone else to contribute that - they only gave me the two values at the time.

**Comment by uded** [comment]
Cool, please do. There are specific ranges for those if you want. But the value there is calculated automatically.
