### ISSUE TITLE
Support for tag 0x31 and 0x40

### ISSUE THREAD

**Issue by uded** [ryanbinns/ttwatch#55]
This one seems to be interesting. First one is 11 bytes while second is 12 bytes in length. I have no clue what those one are about. If anyone can provide me with an example file I will be happy to investigate...

**Comment by ryanbinns** [comment]
`0x31` is cycling cadence. For some reason I missed it when writing the software. It has this structure:
```c
typedef struct
{
    uint32_t wheel_revolutions;
    uint16_t wheel_revolutions_time;
    uint16_t crank_revolutions;
    uint16_t crank_revolutions_time;
} CYCLING_CADENCE_RECORD;
```
I don't have any information for `0x40` yet.

**Comment by uded** [comment]
Great! Added `0x31` in my implementation.

`0x40` seems to arrive with Spark, so it might be connected to one of the new modes...

**Comment by uded** [comment]
`0x40` is connected to Indoor Cycling. No idea yet what it is really...

**Comment by uded** [comment]
Any chance that one of You guys will have a file with proper indoor cycling tracking? I would love to figure this one out...

**Comment by mschaaf** [comment]
Is there a chance that the cycling cadence will be exported to a gpx or tcx file?

**Comment by mipapo** [comment]
@uded If you're still interested. In #108 is a indoor cycling file

**Comment by uded** [comment]
Thanks, already covered that and will commit ASAP
