### ISSUE TITLE
Activities only downloaded once

### ISSUE THREAD

**Issue by derickr** [ryanbinns/ttwatch#60]
For some reason (could be my fault), after I first ran --get-activities as root, it put it nicely in /root/ttwatch/<name>/<time>..., but a subsequent run with my normal user, did not create /home/username/ttwatch with the activities files? Is there a way to reset that?

**Comment by dlenski** [comment]
ttwatch deletes the activity files from the watch after downloading them (as do the official TomTom clients). So they won't be re-fetched on subsequent invocation.

**Comment by ryanbinns** [comment]
As Dan said, activities are deleted after being downloaded so they don't take up storage space on the watch, otherwise the watch storage will fill up and there wouldn't be space for new activities.
