### ISSUE TITLE
Unable to open watch

### ISSUE THREAD

**Issue by weechatter** [ryanbinns/ttwatch#67]
Hello Ryan,

today i got my new TomTom spark cardio+music. I am not able to connect to the watch. i always get "Unable to open watch". At first the version on the watch was 1.0.52 now its the latest version 1.2.0.

I have access to the music partition.

lsusb:
Bus 001 Device 011: ID 1390:7475 TOMTOM B.V. 

edit:
fixed. i had to change the /etc/udev/rules.d/99-tomtom.rules
the ID of the device changed from 1390:7474 to 1390:7475
sorry for the noise

**Comment by ryanbinns** [comment]
No worries. The rules file in the repository has already been updated to account for all three product IDs.
