### ISSUE TITLE
Gym-Activity: Unable to process output format

### ISSUE THREAD

**Issue by weechatter** [ryanbinns/ttwatch#68]
this error appears when i try to convert a "Gym" activity

ttbincnv -all Gym_16-17-07.ttbin

If someone wants the *.ttbin file, contact me

**Comment by ryanbinns** [comment]
Certainly, eventually. I moved house a week ago and everything is still a horrible mess...

**Comment by weechatter** [comment]
no worries. simply leave me a note and where i can send the *ttbin-files
