### ISSUE TITLE
Runner watch firmware not supported

### ISSUE THREAD

**Issue by sjquinney** [ryanbinns/ttwatch#85]
I've been using ttwatch successfully for about 6 months now with my Runner watch (Product ID 0xe9030000) but after having upgraded the firmware to the latest new version - 1.8.52 - I now just get "Firmware version not supported".

**Comment by fake-fur** [comment]
I'm also having this issue but cannot find enough information from the source files to figure out the fix

**Comment by ryanbinns** [comment]
Hi guys,
I have pushed a fix to add support for this firmware version. I hadn't yet had a chance to see if the settings changed between the previous version and this one. They don't seem to have done. If you want to update it yourself in future, the definitions are at the top of `ttwatch.c`, in the `MANIFEST_DEFINITIONS` array.
