### ISSUE TITLE
No activities downloaded from Runner 2

### ISSUE THREAD

**Issue by Unicorn-rzl** [ryanbinns/ttwatch#92]
I now own a Runner 2 Cardio and want to use ttwatch instead of the TomTom bloatware. The watch is recognized and I was able to set it up correctly (initial setup, setting a name for the watch, etc).

The only thing currently not working is getting the activities from the watch, which would be very nice....

Here is what happens:
<pre>ttwatch -v
Product ID:       0xd8070000
BLE Version:      0
Firmware Version: 1.3.27
Watch Name:       Drecksding
Serial Number:    HNxxxxxxxxx</pre>

<pre>ttwatch --list-history
Treadmill:
1: 2016/07/12 14:45:55,  244s,    76.76m,   14 calories
Cycling:
1: 2016/07/12 12:04:31,  499s,  1441.18m,   72 calories
</pre>

<pre>ttwatch -a
Downloading GPSQuickFix data file...
Writing file to watch...
GPSQuickFix data updated
Current firmware is already at latest version</pre>

<pre>
ttwatch --get-activities -s /home/unicorn/ttwatch/foo/
ls /home/unicorn/ttwatch/foo/
(empty)
</pre>

<pre>
ttwatch --list-history
Treadmill:
1: 2016/07/12 14:45:55,  244s,    76.76m,   14 calories
Cycling:
1: 2016/07/12 12:04:31,  499s,  1441.18m,   72 calories
</pre>

I'm using Linux Mint 17.3
<pre>uname -a
Linux 4.4.0-28-generic #47~14.04.1-Ubuntu SMP Fri Jun 24 16:30:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 17.3 Rosa
Release:	17.3
Codename:	rosa
</pre>

Before I dig into your code, I wanted to ask whether there is any way to get more Information why the activities are not downloaded. Can somebody help me with this?

Please let me know if there are relevant information missing. Thank you.

Here is a package dump, I don't know whether this gives useful information:
<pre>
ttwatch --get-activities --packets -s /home/unicorn/ttwatch/foo/

01 16 00 0D 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 

01 02 01 0A 

01 03 02 22 00 

01 03 03 22 00 

01 06 04 20 D8 07 00 00 

01 02 05 0A 

01 06 06 28 00 00 00 00 

01 06 07 28 00 00 00 00 

01 06 08 1F FF FF FF FF 

01 16 09 06 00 00 00 00 00 F2 00 00 00 00 00 00 00 00 00 00 00 00 00 00 

01 16 0A 05 00 00 00 00 00 F2 00 00 00 00 00 00 00 00 01 E1 00 00 00 00 

01 FC 0B 09 00 F2 00 00 00 00 00 F2 3C 3F 78 6D 6C 20 76 65 72 73 69 6F 6E 3D 22 31 2E 30 22 20 65 6E 63 6F 64 69 6E 67 3D 22 55 54 46 2D 38 22 3F 3E 0D 0A 3C 70 72 65 66 65 72 65 6E 63 65 73 20 76 65 72 73 69 6F 6E 3D 22 31 22 20 6D 6F 64 69 66 69 65 64 3D 22 54 75 65 20 31 32 2E 20 4A 75 6C 20 31 35 3A 30 38 3A 34 30 20 32 30 31 36 22 3E 0D 0A 20 20 20 20 3C 77 61 74 63 68 4E 61 6D 65 3E 44 72 65 63 6B 73 64 69 6E 67 3C 2F 77 61 74 63 68 4E 61 6D 65 3E 0D 0A 20 20 20 20 3C 53 79 6E 63 54 69 6D 65 54 6F 50 43 3E 31 3C 2F 53 79 6E 63 54 69 6D 65 54 6F 50 43 3E 0D 0A 20 20 20 20 3C 53 65 6E 64 41 6E 6F 6E 79 6D 6F 75 73 44 61 74 61 3E 30 3C 2F 53 65 6E 64 41 6E 6F 6E 79 6D 6F 75 73 44 61 74 61 3E 0D 0A 20 20 20 20 3C 57 61 74 63 68 57 69 6E 64 6F 77 4D 

01 F9 0C 09 00 F2 00 00 00 00 00 EF 69 6E 69 6D 69 7A 65 64 3E 30 3C 2F 57 61 74 63 68 57 69 6E 64 6F 77 4D 69 6E 69 6D 69 7A 65 64 3E 0D 0A 20 20 20 20 3C 43 6F 6E 66 69 67 55 52 4C 3E 68 74 74 70 73 3A 2F 2F 6D 79 73 70 6F 72 74 73 2E 74 6F 6D 74 6F 6D 2E 63 6F 6D 2F 73 65 72 76 69 63 65 2F 63 6F 6E 66 69 67 2F 63 6F 6E 66 69 67 2E 6A 73 6F 6E 3C 2F 43 6F 6E 66 69 67 55 52 4C 3E 0D 0A 20 20 20 20 3C 65 78 70 6F 72 74 65 72 73 3E 0D 0A 20 20 20 20 20 20 20 20 3C 6F 66 66 6C 69 6E 65 3E 0D 0A 20 20 20 20 20 20 20 20 3C 65 78 70 6F 72 74 20 69 64 3D 22 74 63 78 22 20 61 75 74 6F 4F 70 65 6E 3D 22 30 22 2F 3E 3C 2F 6F 66 66 6C 69 6E 65 3E 0D 0A 20 20 20 20 3C 2F 65 78 70 6F 72 74 65 72 73 3E 0D 0A 3C 2F 70 72 65 66 65 72 65 6E 63 65 73 3E 0D 0A 

01 16 0D 0C 00 00 00 00 00 F2 00 00 00 00 00 00 00 00 00 00 00 00 00 00 

01 06 0E 20 D8 07 00 00 

01 08 0F 21 31 2E 33 2E 32 37 

01 06 10 28 00 00 00 00 

01 16 11 11 00 00 00 00 00 02 00 05 00 00 00 00 00 00 03 C0 00 00 00 00 

01 16 12 12 00 00 00 00 00 71 00 00 00 00 00 00 00 00 00 4A 00 00 00 00 

01 16 13 12 00 00 00 00 00 71 00 01 00 00 00 00 00 00 00 4A 00 00 00 00 

01 16 14 12 00 00 00 00 00 71 00 02 00 00 00 00 00 00 00 62 00 00 00 00 

01 16 15 12 00 00 00 00 00 71 00 03 00 00 00 00 00 00 00 62 00 00 00 00 

01 16 16 12 00 00 00 00 00 71 00 04 00 00 00 00 00 00 00 8C 00 00 00 00 

01 16 17 12 00 00 00 00 00 71 01 00 00 00 00 00 00 00 00 78 00 00 00 00 

01 16 18 12 00 00 00 00 00 71 01 01 00 00 00 00 00 00 00 B2 00 00 00 00 

01 16 19 12 00 00 00 00 00 71 01 02 00 00 00 00 00 00 00 D2 00 00 00 00 

01 16 1A 12 00 00 00 00 00 71 01 03 00 00 00 00 00 00 01 2E 00 00 00 00 

01 16 1B 12 00 00 00 00 00 71 01 04 00 00 00 00 00 00 01 C2 00 00 00 00 

01 16 1C 12 00 00 00 00 00 71 07 00 00 00 00 00 00 00 00 4A 00 00 00 00 

01 16 1D 12 00 00 00 00 00 71 07 01 00 00 00 00 00 00 00 4A 00 00 00 00 

01 16 1E 12 00 00 00 00 00 71 07 02 00 00 00 00 00 00 00 62 00 00 00 00 

01 16 1F 12 00 00 00 00 00 71 07 03 00 00 00 00 00 00 00 62 00 00 00 00 

01 16 20 12 00 00 00 00 00 71 07 04 00 00 00 00 00 00 00 8C 00 00 00 00 

01 16 21 12 00 00 00 00 00 71 08 00 00 00 00 00 00 00 00 3E 00 00 00 00 

01 16 22 12 00 00 00 00 00 71 08 01 00 00 00 00 00 00 00 52 00 00 00 00 

01 16 23 12 00 00 00 00 00 71 08 02 00 00 00 00 00 00 00 7A 00 00 00 00 

01 16 24 12 00 00 00 00 00 71 08 03 00 00 00 00 00 00 00 A2 00 00 00 00 

01 16 25 12 00 00 00 00 00 71 08 04 00 00 00 00 00 00 01 04 00 00 00 00 

01 16 26 12 00 00 00 00 00 71 0B 00 00 00 00 00 00 00 00 78 00 00 00 00 

01 16 27 12 00 00 00 00 00 71 0B 01 00 00 00 00 00 00 00 B2 00 00 00 00 

01 16 28 12 00 00 00 00 00 71 0B 02 00 00 00 00 00 00 00 D2 00 00 00 00 

01 16 29 12 00 00 00 00 00 71 0B 03 00 00 00 00 00 00 01 2E 00 00 00 00 

01 16 2A 12 00 00 00 00 00 71 0B 04 00 00 00 00 00 00 01 C2 00 00 00 00 

01 16 2B 12 00 00 00 00 00 85 00 00 00 00 00 00 00 00 0C 6A 00 00 00 00 

01 16 2C 12 00 00 00 00 00 00 00 ED 00 00 00 00 00 00 02 00 00 00 00 00 

01 16 2D 12 00 00 00 00 00 01 31 00 00 00 00 00 00 00 28 91 00 00 00 00 

01 16 2E 12 00 00 00 00 00 00 00 31 00 00 00 00 00 01 D3 F3 00 00 00 00 

01 16 2F 12 00 00 00 00 00 01 02 00 00 00 00 00 00 00 A1 F8 00 00 00 00 

01 16 30 12 00 00 00 00 00 81 00 01 00 00 00 00 00 00 0E 95 00 00 00 00 

01 16 31 12 00 00 00 00 00 81 00 02 00 00 00 00 00 00 10 C9 00 00 00 00 

01 16 32 12 00 00 00 00 00 81 00 03 00 00 00 00 00 00 10 0E 00 00 00 00 

01 16 33 12 00 00 00 00 00 81 00 04 00 00 00 00 00 00 10 9E 00 00 00 00 

01 16 34 12 00 00 00 00 00 81 00 05 00 00 00 00 00 00 10 2F 00 00 00 00 

01 16 35 12 00 00 00 00 00 81 00 06 00 00 00 00 00 00 10 CF 00 00 00 00 

01 16 36 12 00 00 00 00 00 81 00 07 00 00 00 00 00 00 11 37 00 00 00 00 

01 16 37 12 00 00 00 00 00 81 00 08 00 00 00 00 00 00 11 47 00 00 00 00 

01 16 38 12 00 00 00 00 00 81 00 09 00 00 00 00 00 00 0F 52 00 00 00 00 

01 16 39 12 00 00 00 00 00 81 00 0A 00 00 00 00 00 00 10 EE 00 00 00 00 

01 16 3A 12 00 00 00 00 00 81 00 0B 00 00 00 00 00 00 0F A1 00 00 00 00 

01 16 3B 12 00 00 00 00 00 81 00 0C 00 00 00 00 00 00 0F FA 00 00 00 00 

01 16 3C 12 00 00 00 00 00 81 00 0D 00 00 00 00 00 00 10 C3 00 00 00 00 

01 16 3D 12 00 00 00 00 00 81 00 0E 00 00 00 00 00 00 0F 6A 00 00 00 00 

01 16 3E 12 00 00 00 00 00 81 00 0F 00 00 00 00 00 00 11 5F 00 00 00 00 

01 16 3F 12 00 00 00 00 00 81 00 10 00 00 00 00 00 00 16 30 00 00 00 00 

01 16 40 12 00 00 00 00 00 81 00 11 00 00 00 00 00 00 10 F8 00 00 00 00 

01 16 41 12 00 00 00 00 00 81 00 12 00 00 00 00 00 00 10 A8 00 00 00 00 

01 16 42 12 00 00 00 00 00 81 00 13 00 00 00 00 00 00 12 B8 00 00 00 00 

01 16 43 12 00 00 00 00 00 85 00 02 00 00 00 00 00 00 0C 6A 00 00 00 00 

01 16 44 12 00 00 00 00 00 87 00 00 00 00 00 00 00 00 00 E8 00 00 00 00 

01 16 45 12 00 00 00 00 00 87 00 01 00 00 00 00 00 00 9C 84 00 00 00 00 

01 16 46 12 00 00 00 00 00 87 01 00 00 00 00 00 00 00 02 50 00 00 00 00 

01 16 47 12 00 00 00 00 00 87 01 01 00 00 00 00 00 04 95 10 00 00 00 00 

01 16 48 12 00 00 00 00 00 87 01 02 00 00 00 00 00 00 00 0C 00 00 00 00 

01 16 49 12 00 00 00 00 00 87 02 00 00 00 00 00 00 00 02 50 00 00 00 00 

01 16 4A 12 00 00 00 00 00 87 02 01 00 00 00 00 00 05 41 CE 00 00 00 00 

01 16 4B 12 00 00 00 00 00 87 02 02 00 00 00 00 00 00 00 0C 00 00 00 00 

01 16 4C 12 00 00 00 00 00 87 03 00 00 00 00 00 00 00 02 50 00 00 00 00 

01 16 4D 12 00 00 00 00 00 87 03 01 00 00 00 00 00 05 2D 48 00 00 00 00 

01 16 4E 12 00 00 00 00 00 87 03 02 00 00 00 00 00 00 00 0C 00 00 00 00 

01 16 4F 12 00 00 00 00 00 87 04 00 00 00 00 00 00 00 02 50 00 00 00 00 

01 16 50 12 00 00 00 00 00 87 04 01 00 00 00 00 00 05 CF B2 00 00 00 00 

01 16 51 12 00 00 00 00 00 87 04 02 00 00 00 00 00 00 00 0C 00 00 00 00 

01 16 52 12 00 00 00 00 00 87 05 00 00 00 00 00 00 00 02 50 00 00 00 00 

01 16 53 12 00 00 00 00 00 87 05 01 00 00 00 00 00 05 A8 86 00 00 00 00 

01 16 54 12 00 00 00 00 00 87 05 02 00 00 00 00 00 00 00 0C 00 00 00 00 

01 16 55 12 00 00 00 00 00 87 06 00 00 00 00 00 00 00 02 50 00 00 00 00 

01 16 56 12 00 00 00 00 00 87 06 01 00 00 00 00 00 04 F9 18 00 00 00 00 

01 16 57 12 00 00 00 00 00 87 06 02 00 00 00 00 00 00 00 0C 00 00 00 00 

01 16 58 12 00 00 00 00 00 87 07 00 00 00 00 00 00 00 02 50 00 00 00 00 

01 16 59 12 00 00 00 00 00 87 07 01 00 00 00 00 00 05 D8 70 00 00 00 00 

01 16 5A 12 00 00 00 00 00 87 07 02 00 00 00 00 00 00 00 0C 00 00 00 00 

01 16 5B 12 00 00 00 00 00 87 08 00 00 00 00 00 00 00 02 50 00 00 00 00 

01 16 5C 12 00 00 00 00 00 87 08 01 00 00 00 00 00 05 D9 7E 00 00 00 00 

01 16 5D 12 00 00 00 00 00 87 08 02 00 00 00 00 00 00 00 0C 00 00 00 00 

01 16 5E 12 00 00 00 00 00 87 09 00 00 00 00 00 00 00 02 50 00 00 00 00 

01 16 5F 12 00 00 00 00 00 87 09 01 00 00 00 00 00 03 D0 0C 00 00 00 00 

01 16 60 12 00 00 00 00 00 87 09 02 00 00 00 00 00 00 00 0C 00 00 00 00 

01 16 61 12 00 00 00 00 00 87 0A 00 00 00 00 00 00 00 02 50 00 00 00 00 

01 16 62 12 00 00 00 00 00 87 0A 01 00 00 00 00 00 06 43 84 00 00 00 00 

01 16 63 12 00 00 00 00 00 87 0A 02 00 00 00 00 00 00 00 0C 00 00 00 00 

01 16 64 12 00 00 00 00 00 87 0B 00 00 00 00 00 00 00 02 50 00 00 00 00 

01 16 65 12 00 00 00 00 00 87 0B 01 00 00 00 00 00 05 84 02 00 00 00 00 

01 16 66 12 00 00 00 00 00 87 0B 02 00 00 00 00 00 00 00 0C 00 00 00 00 

01 16 67 12 00 00 00 00 00 87 0C 00 00 00 00 00 00 00 02 50 00 00 00 00 

01 16 68 12 00 00 00 00 00 87 0C 01 00 00 00 00 00 04 DE 7E 00 00 00 00 

01 16 69 12 00 00 00 00 00 87 0C 02 00 00 00 00 00 00 00 0C 00 00 00 00 

01 16 6A 12 00 00 00 00 00 87 0D 00 00 00 00 00 00 00 02 50 00 00 00 00 

01 16 6B 12 00 00 00 00 00 87 0D 01 00 00 00 00 00 06 33 3C 00 00 00 00 

01 16 6C 12 00 00 00 00 00 87 0D 02 00 00 00 00 00 00 00 0C 00 00 00 00 

01 16 6D 12 00 00 00 00 00 87 0E 00 00 00 00 00 00 00 02 50 00 00 00 00 

01 16 6E 12 00 00 00 00 00 87 0E 01 00 00 00 00 00 05 3C A0 00 00 00 00 

01 16 6F 12 00 00 00 00 00 87 0E 02 00 00 00 00 00 00 00 0C 00 00 00 00 

01 16 70 12 00 00 00 00 00 87 0F 00 00 00 00 00 00 00 02 50 00 00 00 00 

01 16 71 12 00 00 00 00 00 87 0F 01 00 00 00 00 00 05 1B 60 00 00 00 00 

01 16 72 12 00 00 00 00 00 87 0F 02 00 00 00 00 00 00 00 0C 00 00 00 00 

01 16 73 12 00 00 00 00 00 01 30 02 00 00 00 00 00 00 00 76 00 00 00 00 

01 16 74 12 00 00 00 00 00 85 00 01 00 00 00 00 00 00 0C 6A 00 00 00 00 

01 16 75 12 00 00 00 00 00 02 00 01 00 00 00 00 00 00 00 48 00 00 00 00 

01 16 76 12 00 00 00 00 00 B2 00 01 00 00 00 00 00 00 00 04 00 00 00 00 

01 16 77 12 00 00 00 00 00 B1 00 06 00 00 00 00 00 00 00 C5 00 00 00 00 

01 16 78 12 00 00 00 00 00 B3 00 0F 00 00 00 00 00 00 07 F5 00 00 00 00 

01 16 79 12 00 00 00 00 00 B1 00 00 00 00 00 00 00 00 00 9A 00 00 00 00 

01 16 7A 12 00 00 00 00 00 F2 00 00 00 00 00 00 00 00 01 E1 00 00 00 00 

01 16 7B 12 00 00 00 00 00 01 01 00 00 00 00 00 00 00 7A D2 00 00 00 00 

01 16 7C 12 00 00 00 00 00 01 01 02 00 00 00 00 00 00 7A D2 00 00 00 00 

01 16 7D 12 00 00 00 00 00 01 01 01 00 00 00 00 00 00 76 98 00 00 00 00 

01 16 7E 12 00 00 00 00 00 B1 00 01 00 00 00 00 00 00 00 99 00 00 00 00 

01 16 7F 12 00 00 00 00 00 B7 00 00 00 00 00 00 00 00 00 B2 00 00 00 00 

01 16 80 12 00 00 00 00 00 82 00 01 00 00 00 00 00 20 C7 02 00 00 00 00 

01 16 81 12 00 00 00 00 00 87 10 00 00 00 00 00 00 00 02 50 00 00 00 00 

01 16 82 12 00 00 00 00 00 87 10 01 00 00 00 00 00 06 A7 58 00 00 00 00 

01 16 83 12 00 00 00 00 00 87 10 02 00 00 00 00 00 00 00 0C 00 00 00 00 

01 16 84 12 00 00 00 00 00 87 13 00 00 00 00 00 00 00 02 50 00 00 00 00 

01 16 85 12 00 00 00 00 00 87 13 01 00 00 00 00 00 07 5C 08 00 00 00 00 

01 16 86 12 00 00 00 00 00 87 13 02 00 00 00 00 00 00 00 0C 00 00 00 00 

01 16 87 12 00 00 00 00 00 85 00 03 00 00 00 00 00 00 08 44 00 00 00 00 

01 16 88 12 00 00 00 00 00 A6 00 00 00 00 00 00 00 1A 13 66 00 00 00 00 

01 16 89 12 00 00 00 00 00 83 00 06 00 00 00 00 00 00 00 54 00 00 00 00 

01 16 8A 12 00 00 00 00 00 B2 00 00 00 00 00 00 00 00 00 C1 00 00 00 00 

01 16 8B 12 00 00 00 00 00 B1 00 02 00 00 00 00 00 00 01 E1 00 00 00 00 

01 16 8C 12 00 00 00 00 00 72 01 00 00 00 00 00 00 00 00 3E 00 00 00 00 

01 16 8D 12 00 00 00 00 00 73 01 00 00 00 00 00 00 00 00 2D 00 00 00 00 

01 16 8E 12 00 00 00 00 00 83 00 02 00 00 00 00 00 00 00 54 00 00 00 00 

01 16 8F 12 00 00 00 00 00 B1 00 03 00 00 00 00 00 00 06 30 00 00 00 00 

01 16 90 12 00 00 00 00 00 B1 00 04 00 00 00 00 00 00 00 90 00 00 00 00 

01 16 91 12 00 00 00 00 00 B1 00 05 00 00 00 00 00 00 01 36 00 00 00 00 

01 16 92 12 00 00 00 00 00 B1 00 08 00 00 00 00 00 00 00 95 00 00 00 00 

01 16 93 12 00 00 00 00 00 72 07 01 00 00 00 00 00 00 00 26 00 00 00 00 

01 16 94 12 00 00 00 00 00 73 07 01 00 00 00 00 00 00 00 2D 00 00 00 00 

01 16 95 12 00 00 00 00 00 B1 00 07 00 00 00 00 00 00 01 C8 00 00 00 00 

01 16 96 12 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 

01 06 97 1A 00 00 11 18 

01 02 98 0A 

01 05 99 23 64 01 00 

01 05 9A 23 64 01 00 </pre>

**Comment by ryanbinns** [comment]
Based on that packet dump, your watch doesn't actually have any activities on it. They may have been downloaded previously. The history items are separate from the activity data. The history items only store enough information to allow the race function to work and show history information on the watch itself. They do not contain the entire logged data.

Once the activities are downloaded, they are deleted from the watch to save storage space, so they can only be downloaded once. If your watch was attached to the computer using the TomTom software after these activities were created, then the activity data is no longer on the watch and cannot be downloaded again.

**Comment by Unicorn-rzl** [comment]
Thank you for the really fast answer!
I've created a new activity on the watch and did:
<pre>
ttwatch --get-activities -s /home/unicorn/ttwatch/foo/
tree /home/unicorn/ttwatch/foo/
/home/unicorn/ttwatch/foo/
└── Drecksding
    └── 2016-07-12
        ├── Treadmill_16-03-20.tcx
        └── Treadmill_16-03-20.ttbin

2 directories, 2 files
</pre>
Hooray! It works!

Then I did another "threadmill" session on my desk and tried the -a option:
<pre>
strace -e trace=write ttwatch -a
write(7, "\1", 1)                       = 1
write(12, " \t\0\1\3\33\330\7\23\26\205W\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0005xp_"..., 1170) = 1170
write(12, "<?xml version=\"1.0\" encoding=\"UT"..., 4096) = 4096
write(12, "        </Extensions>\r\n         "..., 4096) = 4096
write(12, "ion/v2\">\r\n                      "..., 4096) = 4096
write(12, "                        <Extensi"..., 4096) = 4096
write(12, "                   <Time>2016-07"..., 3056) = 3056
write(12, "\26\3\1\1(\1\0\1$\3\3^\0231\2735\245\361E\5JQ\26D\20\235\245\242\334IG\20"..., 301) = 301
write(12, "\26\3\3\1\6\20\0\1\2\1\0R\325\210\372\31\320Y\304\0\366\21\36\362\36&\364\256{\20\21\312"..., 342) = 342
write(12, "\27\3\3\0\240R\221b\226?\35w\274:\330'iK\201E\376\376\252\37\330\26\260\222G\300[x"..., 165) = 165
write(12, "\25\3\3\0000\20V\36\r\222dgt\3120z\1\0161\22\333E~j\315r@\21\331(\240\366"..., 53) = 53
write(1, "Downloading GPSQuickFix data fil"..., 37Downloading GPSQuickFix data file...
) = 37
write(12, "\26\3\1\0014\1\0\0010\3\3\30\263\366\211\35\241vY\212\v\30\217>-\326\305\f\256\370^\244"..., 313) = 313
write(12, "\26\3\3\1\6\20\0\1\2\1\0\207\320/4K\36\4[\30\322\313\240\320\26lQ_\355 \234\216"..., 358) = 358
write(12, "\27\3\3\0\260j\237O\"\223Ou\231`k\16\243{\346+\304Cj\270\357\275\207\327\4\177\374\255"..., 181) = 181
write(12, "\25\3\3\0@\"\26\200\0177\271\355\340\\J\327.m\251IC\353\226\201\266V\253\277\257v\334G"..., 69) = 69
write(1, "Writing file to watch...\n", 25Writing file to watch...
) = 25
write(1, "GPSQuickFix data updated\n", 25GPSQuickFix data updated
) = 25
write(12, "\26\3\1\1(\1\0\1$\3\3Xh\351$:[ \27\332\365\306\32eS\3\247 \202%i,"..., 301) = 301
write(12, "\26\3\3\1\6\20\0\1\2\1\0\314\\W\22#\236\256\302N\245O/\24\374\233L\f\372\313\21\334"..., 342) = 342
write(12, "\27\3\3\0\240\264J[e\271\234F\2\221\303\20&T\320?\31#\364\200E\357\212\270\352R\375\255"..., 165) = 165
write(12, "\25\3\3\0000yTa\225+\26\206\4\242\325\220\250\32x}H\20a\350\354\251|\25\207\352\230\35"..., 53) = 53
write(12, "\26\3\1\1/\1\0\1+\3\3\240\306\232r\253\35\16\206\200&c\270\376\247\225\226\343\16\333+\334"..., 308) = 308
write(12, "\26\3\3\0F\20\0\0BA\4Bi\337\242\200\36\227\20\367CH\16\324\276\214\336_./\305\315"..., 126) = 126
write(12, "\27\3\3\0\251%\221\375\341\266^\25\341?RM\26\363\10\2105e\2 \200\333\356\242\"F\242\375"..., 174) = 174
write(12, "\25\3\3\0\32%\221\375\341\266^\25\342T\0164\340e\354\316\234\362\363\276(\312\260\357\ro~", 31) = 31
write(2, "Current firmware is already at l"..., 46Current firmware is already at latest version
) = 46
write(7, "\1", 1)                       = 1
write(5, "\1", 1)                       = 1
+++ exited with 0 +++
</pre>
<pre>
ttwatch --get-activities -s /home/unicorn/ttwatch/foo/
UniPad unicorn # tree /home/unicorn/ttwatch/foo/
/home/unicorn/ttwatch/foo/
└── Drecksding
    └── 2016-07-12
        ├── Treadmill_16-03-20.tcx
        └── Treadmill_16-03-20.ttbin

2 directories, 2 files
</pre>

So, the -a seems to delete the activities from my watch without saving them?

**Comment by Unicorn-rzl** [comment]
Ok, I was able to find my mistake. ttwatch did download the data, but since I've used a root session, the data got stored in my /root and I failed to look there.
Sorry for the noise, hopefully I can act as a bad example for others who make the same mistake.

**Comment by ryanbinns** [comment]
No worries, I'm glad it's all working now.
