### ISSUE TITLE
Firmware version not supported

### ISSUE THREAD

**Issue by tomisilander** [ryanbinns/ttwatch#97]
Hi,
followed the instructions and installed everything to Ubuntu 16.04. Everything worked perfect so I dared to try to update the old (1.1.19) firmware of my Tomtom runner 2 to the latest version . Even that appeared to go smoothly (I am honestly impressed) but now I get Firmware version not supported :(

ttwatch --update-fw
Current Firmware Version: 0x00010113
Latest Firmware Version : 0x000103a0
Download https://sports.tomtom-static.com/downloads/firmware/D8070000/1_3_160/0x000000F0 ... Done
Download https://sports.tomtom-static.com/downloads/firmware/D8070000/1_3_160/0x00850000 ... Done
Updating firmware file: 000000f0 ... Done
Updating firmware file: 00850000 ... Done
Firmware updated
Waiting for watch to restart.............................................
ttwatch --all-settings 
Firmware version not supported

ts.

**Comment by adzane** [comment]
In this case, adding 

`{ 0x000103a0, MANIFEST_DEFINITION_0001031b_COUNT, MANIFEST_DEFINITIONS_0001031b },`

in ttwatch.c should work. Read similar closed issues for more details.
